import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavigationHeader from "../components/navigation-header";
import Footer from "../components/footer";
import { AccentColorProvider } from "../contexts/accent-color-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const argon = localFont({
  src: [
    {
      path: "../../public/fonts/Argon-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Argon-Oblique.otf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-argon",
});

const mondwest = localFont({
  src: [
    {
      path: "../../public/fonts/Mondwest-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Mondwest-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-mondwest",
  display: "swap",
});

const objectSans = localFont({
  src: [
    {
      path: "../../public/fonts/ObjectSans-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/ObjectSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-object-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${argon.variable} ${mondwest.variable} ${objectSans.variable}`}
      >
        <AccentColorProvider>
          <NavigationHeader />
          {children}
          <Footer />
        </AccentColorProvider>
      </body>
    </html>
  );
}
